
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Instruções: Configure as variáveis de ambiente abaixo no painel do Netlify
# Acesse: Site settings > Build & deploy > Environment > Environment variables
#
# VITE_ACCESS_PASSWORD = "sua_senha_de_acesso"
# VITE_GOOGLE_SHEETS_URL_CLIENTE = "insira na variavel do seu provedor"
# VITE_GOOGLE_SHEETS_URL_LEAD = "insira na variavel do seu provedor"
# VITE_GOOGLE_SHEET_VIEW_URL_CLIENTE = "insira na variavel do seu provedor
# VITE_GOOGLE_SHEET_VIEW_URL_LEAD = "insira na variavel do seu provedor"

