
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Instruções: Configure a variável de ambiente VITE_ACCESS_PASSWORD no painel do Netlify
# Acesse: Site settings > Build & deploy > Environment > Environment variables
